class TestException(Exception):
    pass

class CalculatorException(Exception):
    pass
        